version: "3.9"
services:  
  key-vault:
    container_name: key-vault
    image: vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
  config-server:
    depends_on: 
      - key-vault
    container_name: config-server
    image: canaldopubdev/config-server
    links:
      - "key-vault:vault"
    environment:      
      VAULT_TOKEN: myroot
      VAULT_HOST: key-vault
      VAULT_PORT: 8200
      VAULT_SCHEME: http
      VAULT_URI: http://key-vault:8200
      GIT_REPOSITORY_URI: https://github.com/Pub-Dev/Lesson-DotNet-ConfigServer-Configs
      GIT_DEFAULT_BRANCH: main   
    ports:
      - "8888:8888"